version: '3.9'
services:
  backend:
    container_name: django_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000 && python manage.py makemigrations && python manage.py migrate"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=user_devdb
      - DB_PASS=password
    depends_on:
      - db

  frontend:
    container_name: react_app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    # depends_on:
    #   - backend

  db:
    container_name: mysql_db
    image: mysql:8.3.0
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devdb
      MYSQL_USER: user_devdb
      MYSQL_PASSWORD: password
    volumes:
      - database:/var/lib/mysql

volumes:
  database: