# Generated by Django 5.0.1 on 2024-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscord',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdiscord',
            name='user_picture',
            field=models.ImageField(blank=True, default='user_pictures/Screenshot_2024-02-03_225454_1iAnAPV.png', null=True, upload_to='user_pictures/'),
        ),
    ]
