# Generated by Django 4.0.10 on 2024-02-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiscord',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdiscord',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
