# Generated by Django 5.0.1 on 2024-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0002_userdiscord_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscord',
            name='user_picture',
            field=models.ImageField(blank=True, default='user_pictures/avatar.jpg', null=True, upload_to='user_pictures/'),
        ),
    ]
