# Generated by Django 5.0.1 on 2024-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord', '0005_alter_userdiscord_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdiscord',
            name='user_picture',
            field=models.ImageField(blank=True, default='user_pictures/avatar.jpg', null=True, upload_to='user_pictures'),
        ),
    ]
